### ISSUE TITLE
Why does HB Expert use regex on requests?

### ISSUE THREAD

**Issue by ydennisy** [prebid/header-bidder-expert#3]
Hello,

From looking at the PrebidJS spec it seems you could just call methods on the global window object such as `getAllBids()` to test for the presence of header bidders?

Why the need for intercepting requests with string matching?

Thank you!

**Comment by mkendall07** [comment]
I think the idea is that it will detect HB on sites that don't use prebid.js.

**Comment by ydennisy** [comment]
Thanks @mkendall07, for your reply.

I am testing pages that use prebidjs, please take a look at the following screenshot:
<img width="607" alt="screenshot 2019-02-16 at 19 28 33" src="https://user-images.githubusercontent.com/10243849/53018301-e920ab00-3449-11e9-94ca-4239a6033fcc.png">
Why is there such a disparity between what the `pbjs` object returns and HB expert?

**Comment by ydennisy** [comment]
@mkendall07 any idea on this?

**Comment by dpapworth-qc** [comment]
Looking at pbjs.getBidResponses, it looks like empty bid responses are being filtered (as a by-product of mapping responses to requests). So that would explain why you only see a subset of the bidders in the call response.

**Comment by patmmccann** [comment]
HB Expert is deprecated
